### ISSUE TITLE
GMLib Rio 1.5.5 stopped working

### ISSUE THREAD

**Issue by vpapanik** [wos83/GMLibDelphiRio#1]
Hello,

All programs using GMLib 1.5.5 have stopped working (including MegaDemo). The error message is

![image](https://user-images.githubusercontent.com/22118061/155116405-f09e3e4d-35a5-43a0-96c4-a196828fc67c.png)

![image](https://user-images.githubusercontent.com/22118061/155116470-b4478ce5-527a-43b5-8307-5dac205b2695.png)

Is there any way to fix this problem ?

**Comment by vpapanik** [comment]
I also tried to compile it with TChromium, but it cannot be compiled with its latest version.

**Comment by cfatihb** [comment]
i hope they solve this problem.

**Comment by vpapanik** [comment]
solved here 

https://github.com/cadetill/gmlib_v1/issues/16
